spring:
  datasource:
    url: jdbc:mysql://localhost:3306/score?serverTimezone=Asia/Seoul
    username: root
    password: Kamilaezail21!
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true